version: '3.8'

services:
  herakoi-web-simple:
    build: . 
    container_name: herakoi_web_simple_dev
    ports:
      - "7070:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    command: /bin/sh -c "nginx -g 'daemon off;'" & /bin/sh -c "while inotifywait -r -e modify /usr/share/nginx/html; do nginx -s reload; done"
