
version: '3.8'

services:
  herakoi-web-simple:
    build: .
    container_name: herakoi_web_simple
    ports:
      - "7070:80" # Maps port 80 in the container to 8080 on your machine
    restart: unless-stopped
